/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.107
 * Generated at: 2021-03-26 06:19:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp._09;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.net.URLEncoder;

public final class cookieDesc_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>09/cookieDesc.jsp</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<h4>Cookie</h4>\r\n");
      out.write("<pre>\r\n");
      out.write("\t: Http의 stateless 특성을 보완하기 위해 최소한의 상태 정보를 저장하는 개념\r\n");
      out.write("\t\t1. session : 상태 정보를 서버 사이드에서 유지.\r\n");
      out.write("\t\t2. cookie : 상태 정보를 클라이언트 사이드에서 유지.\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t** 쿠키 사용 방법\r\n");
      out.write("\t\t");

			Cookie sampleCookie = new Cookie("sampleCookie", "CookieValue");
			response.addCookie(sampleCookie);
			
			String koreanValue = URLEncoder.encode("한글쿠키", "UTF-8");
			
			Cookie koreanCookie = new Cookie("koreanCookie", koreanValue);
			response.addCookie(koreanCookie);
			
			Cookie allDomain = new Cookie("allDomainCookie", "all domain");
			allDomain.setDomain(".kdy.com");
			response.addCookie(allDomain);
		
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t(서버사이드 기준)\r\n");
      out.write("\t\t1. 쿠키 생성\r\n");
      out.write("\t\t2. 응답에 쿠키를 포함하여 전송(Response Header 쿠키가 서버에서 만들어졌기 때문에 클라이언트로 보내야한다.)\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t(클라이언트 사이드)\r\n");
      out.write("\t\t3. 쿠키가 브라우저가 가진 저장소에 저장(한 클라이언트가 여러 개의 브라우저를 사용하고 있다면 저장소도 여러개)\r\n");
      out.write("\t\t4. 저장되어 있던 쿠키가 다음 번 요청에 실려 재전송된다.(Request Header)\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t(다시 서버 사이드)\r\n");
      out.write("\t\t5. 요청에 포함된 쿠키를 꺼내서 상태를 복원한다.<a href=\"cookieView.jsp\">쿠키 확인하기(동일경로)</a>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t** 쿠키 속성의 종류\r\n");
      out.write("\t\t1. name(required) : 공백포함X, 특수문자X, _사용가능 (자바에서 사용하는 변수 선언 규칙과 동일)\r\n");
      out.write("\t\t2. value(required) : 특수문자를 포함하는 경우, RFC2396 규약에 따라 url encoding 방식을 사용한다.(복원시-decoding)\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t-----optional\r\n");
      out.write("\t\t3. domain(host) \r\n");
      out.write("\t\t4. path\r\n");
      out.write("\t\t5. maxAge(expires)\r\n");
      out.write("\t\t6. httpOnly\r\n");
      out.write("\t\t7. secure\r\n");
      out.write("\t\t\r\n");
      out.write("</pre>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
