/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.107
 * Generated at: 2021-03-04 05:57:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import kr.or.ddit.vo.MemberVO;
import java.util.List;

public final class memberList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>MemberList 페이지</title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("  window.onload = function(){\r\n");
      out.write("\t  var addBtn = document.getElementById(\"addBtn\");\r\n");
      out.write("\t  addBtn.onclick = function(){\r\n");
      out.write("\t\t  location.href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberForm.ddit\";\r\n");
      out.write("\t  }\r\n");
      out.write("  }\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  <h2>회원 목록 보기</h2>\r\n");
      out.write("  <table border=\"1\">\r\n");
      out.write("  <thead>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t  <td colspan=\"4\"><input type=\"button\" id=\"addBtn\" value=\"회원추가\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t  <th>ID</th><th>이  름</th><th>전화번호</th><th>주   소</th>\r\n");
      out.write("\t</tr>\r\n");
      out.write("  </thead>\r\n");
      out.write("  <tbody>\r\n");
      out.write("  ");

  	// 서블릿에서 보내온 데이터를 출력한다.
  	List<MemberVO> memList = (List<MemberVO>)request.getAttribute("memList");
    
    if(memList == null || memList.size() == 0){
  
      out.write("\r\n");
      out.write("\t<tr><td colspan=\"4\">회원이 하나도 없습니다.</td></tr>\r\n");
      out.write("  ");
    	
    }else{
    	for(MemberVO memVo : memList){
  
      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t  <td>\r\n");
      out.write("\t    <a href=\"");
      out.print(request.getContextPath());
      out.write("/member/memberView.ddit?mem_id=");
      out.print(memVo.getMem_id());
      out.write('"');
      out.write('>');
      out.print(memVo.getMem_id() );
      out.write("</a>\r\n");
      out.write("\t  </td>\r\n");
      out.write("\t  <td>");
      out.print(memVo.getMem_name() );
      out.write("</td>\r\n");
      out.write("\t  <td>");
      out.print(memVo.getMem_tel() );
      out.write("</td>\r\n");
      out.write("\t  <td>");
      out.print(memVo.getMem_addr() );
      out.write("</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\r\n");
      out.write("  ");
  	
    	}
    }
  
      out.write("\r\n");
      out.write("  </tbody>\r\n");
      out.write("  </table>\r\n");
      out.write("  \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
