/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.63
 * Generated at: 2021-03-22 08:35:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.blood;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class b_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<p style=\"TEXT-ALIGN: center\">\r\n");
      out.write("\t\t<strong><span style=\"COLOR: #ff0000\">B형</span></strong>\r\n");
      out.write("\t</p>\r\n");
      out.write("\t<p style=\"TEXT-ALIGN: center\">\r\n");
      out.write("\t\t대체적으로 <strong><span style=\"COLOR: #6600ff\">자기중심적</span></strong>입니다.\r\n");
      out.write("\t</p>\r\n");
      out.write("\t<p style=\"TEXT-ALIGN: center\">\r\n");
      out.write("\t\t그러므로 <strong><span style=\"COLOR: #6600ff\">규율이나 규칙, 속박을\r\n");
      out.write("\t\t</span></strong>\r\n");
      out.write("\t</p>\r\n");
      out.write("\t<p style=\"TEXT-ALIGN: center\">\r\n");
      out.write("\t\t<strong><span style=\"COLOR: #6600ff\">극히 싫어하기 </span></strong>마련입니다.\r\n");
      out.write("\t</p>\r\n");
      out.write("\t<p style=\"TEXT-ALIGN: center\">\r\n");
      out.write("\t\t또한 자신이 <strong>좋아하는 일에 몰두하는 </strong>\r\n");
      out.write("\t</p>\r\n");
      out.write("\t<p style=\"TEXT-ALIGN: center\">파워를 가지고 있지만</p>\r\n");
      out.write("\t<p style=\"TEXT-ALIGN: center\">\r\n");
      out.write("\t\t<strong><span style=\"COLOR: #6600ff\">싫어하는 일엔 무관심하기까지 </span></strong>합니다.\r\n");
      out.write("\t</p>\r\n");
      out.write("\t<p style=\"TEXT-ALIGN: center\">이렇듯 속박을 싫어하기 때문에</p>\r\n");
      out.write("\t<p style=\"TEXT-ALIGN: center\">\r\n");
      out.write("\t\t생각이 <strong><span style=\"COLOR: #6600ff\">유연</span></strong>하고<strong><span\r\n");
      out.write("\t\t\tstyle=\"COLOR: #6600ff\"> 기발한 </span><span style=\"COLOR: #6600ff\">발상</span></strong>에\r\n");
      out.write("\t\t뛰어납니다.\r\n");
      out.write("\t</p>\r\n");
      out.write("\t<p style=\"TEXT-ALIGN: center\">대인관계는 독선적이기는 하나</p>\r\n");
      out.write("\t<p style=\"TEXT-ALIGN: center\">솔직하게 감정이 드러나고도</p>\r\n");
      out.write("\t<p style=\"TEXT-ALIGN: center\">\r\n");
      out.write("\t\t또 행동으로 옮겨지기에 <strong><span style=\"COLOR: #6600ff\">변덕</span></strong>스럽다는\r\n");
      out.write("\t</p>\r\n");
      out.write("\t<p style=\"TEXT-ALIGN: center\">말을 많이 듣습니다.</p>\r\n");
      out.write("\t<p style=\"TEXT-ALIGN: center\">많은 친구들을 가지고 있지만</p>\r\n");
      out.write("\t<p style=\"TEXT-ALIGN: center\">진짜 친구는 소수라고 여기고 또</p>\r\n");
      out.write("\t<p style=\"TEXT-ALIGN: center\">누구도 자신을 알 수 없다고 여기는</p>\r\n");
      out.write("\t<p style=\"TEXT-ALIGN: center\">\r\n");
      out.write("\t\t<strong><span style=\"COLOR: #6600ff\">폐쇄주의</span></strong>도 가끔 보입니다.\r\n");
      out.write("\t</p>\r\n");
      out.write("\t<p style=\"TEXT-ALIGN: center\">하지만 B형은 주기적으로</p>\r\n");
      out.write("\t<p style=\"TEXT-ALIGN: center\">\r\n");
      out.write("\t\t슬퍼하는 일종의 <strong><span style=\"COLOR: #6600ff\">소외감</span></strong>을 느끼는\r\n");
      out.write("\t\t것이\r\n");
      out.write("\t</p>\r\n");
      out.write("\t<p style=\"TEXT-ALIGN: center\">일반적인 경우입니다.</p>\r\n");
      out.write("\t<p style=\"TEXT-ALIGN: center\">\r\n");
      out.write("\t\t자신이 집단에 적응하기보단 <strong><span style=\"COLOR: #6600ff\">집단을</span></strong>\r\n");
      out.write("\t</p>\r\n");
      out.write("\t<p style=\"TEXT-ALIGN: center\">\r\n");
      out.write("\t\t<strong><span style=\"COLOR: #6600ff\">자기에 적응</span></strong>시킵니다.\r\n");
      out.write("\t</p>\r\n");
      out.write("\t<p style=\"TEXT-ALIGN: center\">\r\n");
      out.write("\t\t<strong><span style=\"COLOR: #6600ff\">경쟁의식</span></strong>과 <strong><span\r\n");
      out.write("\t\t\tstyle=\"COLOR: #6600ff\">열등감</span></strong>도 꽤 있는 편입니다.\r\n");
      out.write("\t</p>\r\n");
      out.write("\t<p style=\"TEXT-ALIGN: center\">이러한 여러가지 강한 면들 때문에</p>\r\n");
      out.write("\t<p style=\"TEXT-ALIGN: center\">B형들의 말들은 단정적이고</p>\r\n");
      out.write("\t<p style=\"TEXT-ALIGN: center\">다소 과장적인 면이 있습니다.</p>\r\n");
      out.write("\t<p style=\"TEXT-ALIGN: center\">이러한 B형들의 감정은 그들의 본능적인</p>\r\n");
      out.write("\t<p style=\"TEXT-ALIGN: center\">생명력에서 옵니다. &nbsp;</p>\r\n");
      out.write("\t<p style=\"TEXT-ALIGN: center\">그래서 실제로 돈이나 명예 등을</p>\r\n");
      out.write("\t<p style=\"TEXT-ALIGN: center\">생각하지 않고 그저 일한다는 즐거움으로</p>\r\n");
      out.write("\t<p style=\"TEXT-ALIGN: center\">움질일 수 있고</p>\r\n");
      out.write("\t<p style=\"TEXT-ALIGN: center\">\r\n");
      out.write("\t\t또 하찮은 이유로 모든 것을<strong><span style=\"COLOR: #6600ff\">\r\n");
      out.write("\t\t\t\t쉽게 </span></strong>\r\n");
      out.write("\t</p>\r\n");
      out.write("\t<p style=\"TEXT-ALIGN: center\">\r\n");
      out.write("\t\t<strong><span style=\"COLOR: #6600ff\">포기</span></strong>할 수 있습니다.\r\n");
      out.write("\t</p>\r\n");
      out.write("\t<p style=\"TEXT-ALIGN: center\">무엇에든 감정적 흥미가 사라지면</p>\r\n");
      out.write("\t<p style=\"TEXT-ALIGN: center\">집착하기 힘들기 때문입니다.</p>\r\n");
      out.write("\t<p style=\"TEXT-ALIGN: center\">B형은 주로 가벼운 마음으로</p>\r\n");
      out.write("\t<p style=\"TEXT-ALIGN: center\">우정같은데서 사랑이 시작하여</p>\r\n");
      out.write("\t<p style=\"TEXT-ALIGN: center\">점차로 깊어지면서 상대방을 기쁘게</p>\r\n");
      out.write("\t<p style=\"TEXT-ALIGN: center\">\r\n");
      out.write("\t\t<a title=\"글자색\" class=\"tx-icon\" href=\"javascript:;\"><u><font\r\n");
      out.write("\t\t\t\tcolor=\"#0066cc\">글자색</font></u></a>하기 위하여 바쁘게 움직이고\r\n");
      out.write("\t</p>\r\n");
      out.write("\t<p style=\"TEXT-ALIGN: center\">여기저기 자랑하는 면도</p>\r\n");
      out.write("\t<p style=\"TEXT-ALIGN: center\">가지고 있습니다.</p>\r\n");
      out.write("\t<p style=\"TEXT-ALIGN: center\">&nbsp;</p>\r\n");
      out.write("\t<div align=\"center\">\r\n");
      out.write("\t\t<script src=\"//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js\"\r\n");
      out.write("\t\t\tasync=\"\"></script>\r\n");
      out.write("\t\t<!-- 포스팅가운데336280 -->\r\n");
      out.write("\t\t<ins class=\"adsbygoogle\"\r\n");
      out.write("\t\t\tstyle=\"HEIGHT: 280px; WIDTH: 336px; DISPLAY: inline-block\"\r\n");
      out.write("\t\t\tdata-ad-slot=\"2588759899\" data-ad-client=\"ca-pub-5108690308438926\"\r\n");
      out.write("\t\t\tdata-adsbygoogle-status=\"done\">\r\n");
      out.write("\t\t\t<ins id=\"aswift_2_expand\"\r\n");
      out.write("\t\t\t\tstyle=\"display: inline-table; border: none; height: 280px; margin: 0; padding: 0; position: relative; visibility: visible; width: 336px; background-color: transparent;\">\r\n");
      out.write("\t\t\t\t<ins id=\"aswift_2_anchor\"\r\n");
      out.write("\t\t\t\t\tstyle=\"display: block; border: none; height: 280px; margin: 0; padding: 0; position: relative; visibility: visible; width: 336px; background-color: transparent;\">\r\n");
      out.write("\t\t\t\t\t<iframe id=\"aswift_2\" name=\"aswift_2\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"left: 0; position: absolute; top: 0; border: 0; width: 336px; height: 280px;\"\r\n");
      out.write("\t\t\t\t\t\tsandbox=\"allow-forms allow-popups allow-popups-to-escape-sandbox allow-same-origin allow-scripts allow-top-navigation-by-user-activation\"\r\n");
      out.write("\t\t\t\t\t\twidth=\"336\" height=\"280\" frameborder=\"0\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"https://googleads.g.doubleclick.net/pagead/ads?client=ca-pub-5108690308438926&amp;output=html&amp;h=280&amp;slotname=2588759899&amp;adk=3936346406&amp;adf=2853229247&amp;w=336&amp;lmt=1599115394&amp;psa=0&amp;guci=2.2.0.0.2.2.0.0&amp;format=336x280&amp;url=https%3A%2F%2Fisarang2u.tistory.com%2F73&amp;flash=0&amp;wgl=1&amp;adsid=ChEI8IW9-gUQlfKl1K_yoZfqARIvAB6otklTMWOtuJcU1F5_Wtrn1-S8x--V9rSlRd_6qwMTA6oZIcvjzIxTu6Xgw-0&amp;dt=1599115394079&amp;bpp=1&amp;bdt=391&amp;idt=252&amp;shv=r20200831&amp;cbv=r20190131&amp;ptt=9&amp;saldr=aa&amp;abxe=1&amp;cookie=ID%3D1d194c230baca6ea%3AT%3D1599115395%3AS%3DALNI_MZYhMOKxL-TzTS4LMox9smqIB78wQ&amp;prev_fmts=336x280%2C336x280%2C0x0&amp;nras=1&amp;correlator=5608533672691&amp;frm=20&amp;pv=1&amp;ga_vid=1253255635.1599115394&amp;ga_sid=1599115394&amp;ga_hid=1107390924&amp;ga_fc=0&amp;iag=0&amp;icsg=11178223337472&amp;dssz=67&amp;mdo=0&amp;mso=0&amp;u_tz=540&amp;u_his=3&amp;u_java=0&amp;u_h=902&amp;u_w=1603&amp;u_ah=862&amp;u_aw=1603&amp;u_cd=24&amp;u_nplug=3&amp;u_nmime=4&amp;adx=472&amp;ady=3891&amp;biw=1587&amp;bih=760&amp;scr_x=0&amp;scr_y=876&amp;eid=21066393&amp;oid=3&amp;pvsid=267282743056641&amp;pem=447&amp;ref=https%3A%2F%2Fwww.google.com%2F&amp;rx=0&amp;eae=0&amp;fc=896&amp;brdim=0%2C0%2C0%2C0%2C1603%2C0%2C1603%2C862%2C1604%2C760&amp;vis=1&amp;rsz=%7C%7CoEebr%7C&amp;abl=CS&amp;pfx=0&amp;fu=8192&amp;bc=31&amp;jar=2020-09-03-06&amp;ifi=3&amp;uci=a!3&amp;btvi=2&amp;fsb=1&amp;xpc=LffymWM56X&amp;p=https%3A//isarang2u.tistory.com&amp;dtd=684\"\r\n");
      out.write("\t\t\t\t\t\tmarginwidth=\"0\" marginheight=\"0\" vspace=\"0\" hspace=\"0\"\r\n");
      out.write("\t\t\t\t\t\tallowtransparency=\"true\" scrolling=\"no\" allowfullscreen=\"true\"\r\n");
      out.write("\t\t\t\t\t\tdata-google-container-id=\"a!3\"\r\n");
      out.write("\t\t\t\t\t\tdata-google-query-id=\"CMGBm4mxzOsCFWGQwgodRUIOgw\"\r\n");
      out.write("\t\t\t\t\t\tdata-load-complete=\"true\"></iframe>\r\n");
      out.write("\t\t\t\t</ins>\r\n");
      out.write("\t\t\t</ins>\r\n");
      out.write("\t\t</ins>\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\t(adsbygoogle = window.adsbygoogle || []).push({});\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<p>&nbsp;</p>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
